version: '3.5'

services:
  database:
    image: mysql:8
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: resume
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3307:3306

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html/:delegated
    ports:
      - 8000:80

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8002:80

volumes:
  database: ~
