name: PHP Composer

on:
  push:
    branches: [ main, master, cicd ]
  pull_request:
    branches: [ main, master, cicd ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: '7.4'
          version: 2
          args: --profile --ignore-platform-reqs

      #      - name: PHPStan Static Analysis
      #        uses: php-actions/phpstan@v2
      #        with:
      #          configuration: phpstan.neon

      - name: PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          php_version: '7.4'
          version: 8
          configuration: phpunit.xml.dist
          args: --coverage-text


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
