name: Test

on:
  push:
    branches: [ main, cicd ]
  pull_request:
    branches: [ main, cicd ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          php_version: '7.4'
          php_extensions: xdebug
          version: 8
          configuration: phpunit.xml.dist
          args: --coverage-text
